cloud:
  aws:
    s3:
      bucket: eric-s3-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # ???? ??? ???? (default: true)
      file-size-threshold: 0B # ??? ???? ???? ?? ???? ???? ?? ?? (default: 0B)
      location: /users/charming/temp # ???? ??? ??? ???? ??? ?? (default: WAS? ??)
      max-file-size: 100MB # ?? ??? ?? ??? (default: 1MB)
      max-request-size: 100MB # ?? ??? ?? ??? (default: 10MB)