cloud:
  aws:
    s3:
      bucket: eric-s3-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true # ???? ??? ???? (default: true)
      file-size-threshold: 0B # ??? ???? ???? ?? ???? ???? ?? ?? (default: 0B)
      location: /users/charming/temp # ???? ??? ??? ???? ??? ?? (default: WAS? ??)
      max-file-size: 100MB # ?? ??? ?? ??? (default: 1MB)
      max-request-size: 100MB # ?? ??? ?? ??? (default: 10MB)

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400